// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RetailCompare.API.Data;

#nullable disable

namespace RetailCompare.API.Migrations
{
    [DbContext(typeof(RetailCompareDbContext))]
    [Migration("20260924223828_SeedInitialProducts")]
    partial class SeedInitialProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("RetailCompare.Shared.models.PriceHistoryDto", b =>
                {
                    b.Property<string>("StoreName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsOnSale")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("StoreName", "Timestamp");

                    b.ToTable("PriceHistories");

                    b.HasData(
                        new
                        {
                            StoreName = "SuperStore",
                            Timestamp = new DateTime(2026, 9, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsOnSale = true,
                            Price = 32.99m
                        },
                        new
                        {
                            StoreName = "ValueMart",
                            Timestamp = new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsOnSale = false,
                            Price = 35.50m
                        });
                });

            modelBuilder.Entity("RetailCompare.Shared.models.ProductDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CurrentLowestPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Groceries",
                            CurrentLowestPrice = 32.99m,
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Full Cream Milk 2L"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Bakery",
                            CurrentLowestPrice = 16.50m,
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "White Bread 700g"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Pantry",
                            CurrentLowestPrice = 119.99m,
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Instant Coffee 200g"
                        });
                });

            modelBuilder.Entity("RetailCompare.Shared.models.WatchlistRequest", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TargetPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "ProductId");

                    b.ToTable("Watchlists");
                });
#pragma warning restore 612, 618
        }
    }
}
